version: '3.8'

services:
  postgres:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DATABASE
    ports:
      - $POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT
    volumes:
      - db:$DB_DOCKER_PATH

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $PGADMIN_LOCAL_PORT:$PGADMIN_DOCKER_PORT
    environment:
      - PGADMIN_DEFAULT_EMAIL:$PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD:$PGADMIN_DEFAULT_PASSWORD
    stdin_open: true
    tty: true

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: $DB_LOCAL_PATH
      o: bind
